### ISSUE TITLE
black outlines around the torches

### ISSUE THREAD

**Issue by WuschelWookie** [LarsMans64/InfinityButtons#17] opened 2022-11-11 20:51 UTC
Hello, I really like this mod and I wanted to include it in my World. But it seems that I have a problem. All torches have some kind of black outline around them. This outline disappears as soon as I activate the torch. I am playing on the newest version of minecraft 1.19.2 and I only use your mod and "Cloth Config". Maybe there is something wrong in my settings but I havent found a solution yet.

**Comment by WuschelWookie** [comment] 2022-11-11 21:02
![2022-11-11_21 38 40](https://user-images.githubusercontent.com/103684286/201430142-4c5ee991-7f47-46e7-87ae-bd0dfb0a7a57.png)

**Comment by WuschelWookie** [comment] 2022-11-11 21:05
Sry, I am new with this whole github thing. Is there anything else I have to upload?

**Comment by curryducker** [comment] 2022-11-11 21:07
should be plenty for this issue :)

**Comment by curryducker** [comment] 2022-11-11 21:25
![image](https://user-images.githubusercontent.com/66020230/201432822-12a07912-3e90-44c7-8f28-b1479cec7088.png)
sooo, now i'm confused. you are sure you only use those two mods and not some kind of render mod like rubidium or optifine?

**Comment by curryducker** [comment] 2022-11-11 21:38
or some kind of resource pack? because it looks like the issue has something to do with vanilla block models. do the normal torches (not buttons or levers) also have this issue?

**Comment by WuschelWookie** [comment] 2022-11-11 21:46
I was planning on using oculus, which is a forge- and shaderfriendly mod like optifine. In the beginning I was using a shader and thought this is the cause of the problem. But then I started minecraft with just your mod and without any shader or resource pack and it was still there (like in the screenshot).

**Comment by curryducker** [comment] 2022-11-11 21:50
That's weird. The issue is not present when the torches are activated? Then i will try something tomorrow and hopefully that works, we'll see.

**Comment by WuschelWookie** [comment] 2022-11-11 21:50
OMG, okay I am stupid. I figured it out. You dont have to think about it anymore. I was just checking my resource packs ingame and saw that the "Mod Resources" were below the normal minecraft recouces. Well, I moved it above and noww everything is fine

**Comment by WuschelWookie** [comment] 2022-11-11 21:51
I am sry for all that work you probably did. But in the end you helped me with your commend which guided me back to the recource folder

**Comment by curryducker** [comment] 2022-11-11 21:52
Ah that confirms my fix, after next update there will be no dependency on the vanilla model anymore so it won't happen again to anyone :)

**Comment by curryducker** [comment] 2022-11-11 21:53
I will close the issue if i've fixed it

**Comment by WuschelWookie** [comment] 2022-11-11 21:53
But still: Thank you for your help and fast replies. Maybe add some big text on curseforge which tells dumb people like me that they have to move the resources xD

**Comment by curryducker** [comment] 2022-11-12 08:11
fixed in [70bc70f](https://github.com/curryducker/InfinityButtonsForge-1.19.x/commit/70bc70f65d689576b049e6e1dba8c36fb4d4a9f6)

**Closed as completed by curryducker** 2022-11-12 08:11 UTC
